msgid ""
msgstr ""
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-01-20 13:23+0000\n"
"Language: en-US\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: apps/auth/views.py:46
msgid "The authentication data is from more than a day ago."
msgstr ""

#: apps/auth/views.py:49
msgid "The authentication data is not related to the Telegram user!"
msgstr ""

#: apps/tdlib/views.py:28
msgid "Invalid offset."
msgstr ""

#: apps/tdlib/views.py:32
msgid "Invalid limit."
msgstr ""

#: apps/tdlib/views.py:36 apps/tdlib/views.py:98 apps/tdlib/views.py:146
#: apps/tdlib/views.py:215
msgid "Invalid parent_id."
msgstr ""

#: apps/tdlib/views.py:53 apps/tdlib/views.py:78 apps/tdlib/views.py:114
#: apps/tdlib/views.py:165 apps/tdlib/views.py:234 apps/tdlib/views.py:323
msgid "Parent folder not found."
msgstr ""

#: apps/tdlib/views.py:95 apps/tdlib/views.py:143
msgid "Invalid folder_name."
msgstr ""

#: apps/tdlib/views.py:117 apps/tdlib/views.py:168
msgid "A folder with this name already exists."
msgstr ""

#: apps/tdlib/views.py:140 apps/tdlib/views.py:177
msgid "Invalid folder_id."
msgstr ""

#: apps/tdlib/views.py:159 apps/tdlib/views.py:181
msgid "folder_id not found."
msgstr ""

#: apps/tdlib/views.py:204 apps/tdlib/views.py:249 apps/tdlib/views.py:349
msgid "Invalid file_id."
msgstr ""

#: apps/tdlib/views.py:212
msgid "Invalid file_name."
msgstr ""

#: apps/tdlib/views.py:228 apps/tdlib/views.py:253 apps/tdlib/views.py:354
#: apps/tdlib/views.py:390
msgid "file_id not found."
msgstr ""

#: apps/tdlib/views.py:237 apps/tdlib/views.py:329
msgid "A file with this name already exists."
msgstr ""

#: apps/tdlib/views.py:240 apps/tdlib/views.py:332
msgid "A file with this name temporarily reserved."
msgstr ""

#: apps/tdlib/views.py:269
msgid "Invalid file_part."
msgstr ""

#: apps/tdlib/views.py:274
msgid "Invalid file object."
msgstr ""

#: apps/tdlib/views.py:279
msgid "Invalid total_parts."
msgstr ""

#: apps/tdlib/views.py:284 apps/tdlib/views.py:298
msgid "Invalid file_size."
msgstr ""

#: apps/tdlib/views.py:287
msgid "The file size must be less or equal to 2 GB."
msgstr ""

#: apps/tdlib/views.py:291
msgid "The file part size must be less or equal to 512 KB."
msgstr ""

#: apps/tdlib/views.py:295
msgid "The file part size must be evenly divisible by 1024."
msgstr ""

#: apps/tdlib/views.py:303
msgid "total_parts must be {}."
msgstr ""

#: apps/tdlib/views.py:308
msgid "Provided file_size is not equal to the actual file size."
msgstr ""

#: apps/tdlib/views.py:313
msgid "Invalid md5_checksum."
msgstr ""

#: apps/tdlib/views.py:319
msgid "Invalid parent."
msgstr ""

#: apps/tdlib/views.py:326 apps/tdlib/views.py:362
msgid "Invalid file name."
msgstr ""

#: apps/tdlib/views.py:358
msgid "File with id {} successfully uploaded before."
msgstr ""

#: apps/tdlib/views.py:366
msgid "You must upload part {} now."
msgstr ""

#: apps/tdlib/views.py:371
msgid "The file part size must be equal to {} KB."
msgstr ""

#: apps/tdlib/views.py:376
msgid "The file part size must be less or equal to {} KB."
msgstr ""

#: apps/tdlib/views.py:425
msgid "Invalid Range header."
msgstr ""

#: apps/tdlib/views.py:430
msgid "Range length must be less or equal to 1 MB."
msgstr ""

#: apps/tdlib/views.py:440
msgid "The requested file is too big. Please use range request instead."
msgstr ""

#: baseapi/settings.py:21
msgid "English"
msgstr ""
